# Generated by Django 3.0.6 on 2020-07-01 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='ClassName',
        ),
        migrations.AddField(
            model_name='class',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_1.Student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_1.Class'),
        ),
    ]
